In [1]:
import numpy as np

##Linear Algebra

creating a vector

In [2]:
[2, 4, 6, 8, 10]

[2, 4, 6, 8, 10]

In [3]:
import numpy as np
vector = np.array([2, 4, 6, 8, 10])
print(vector)

[ 2  4  6  8 10]


In [4]:
#Vector Addition
import numpy as np
vector1 = np.array([2, 4, 6, 8, 10])
vector2 = np.array([1, 3, 5, 7, 9])
vector3 = vector1 + vector2
print(vector3)

[ 3  7 11 15 19]


In [ ]:
#multiply a vector by a scalar
import numpy as np
vector = np.array([3,6,9])
result = vector * 4
print(result)

[12 24 36]


In [ ]:
#length of a vector
import numpy as np
vector = np.array([3,4])
length = np.linalg.norm(vector)
print(length)

5.0


In [ ]:
#Dot productt
import numpy as np
A = np.array([2,3])
B = np.array([4,5])
dot = np.dot(A,B)
print(dot)

23


In [ ]:
#Normalize the vector
import numpy as np
vector = np.array([6,8])
magnitude = np.linalg.norm(vector)
normalized = vector / magnitude
print(normalized)

[0.6 0.8]


In [13]:
vector = np.array([10,20,30,40])
res=vector*5
print(res)

[ 50 100 150 200]


#Scaler    scalar is a single numerical value.

In [14]:
import numpy as np
scalar = np.array(25)
print(scalar)
print(type(scalar))

25
<class 'numpy.ndarray'>


##Matrix

In [15]:
import numpy as np
matrix = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(matrix)
print(matrix.shape)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
(3, 3)


In [16]:
#Access Matrix Elements
import numpy as np
matrix = np.array([
    [5,10,15],
    [20,25,30],
    [35,40,45]
])
print(matrix[1,1])      
print(matrix[2,2])      
print(matrix[0])        
print(matrix[:,1])      

25
45
[ 5 10 15]
[10 25 40]


##Create a Tensor

In [25]:
import numpy as np
numpy_tensor = np.array([
    [[1, 2, 3], [4, 5, 6]],
    [[7, 8, 9], [10, 11, 12]]
])
print(type(numpy_tensor)) 
print(numpy_tensor.shape)   


<class 'numpy.ndarray'>
(2, 2, 3)


In [26]:
import numpy as np
scalar = np.array(10)
vector = np.array([1,2,3])
matrix = np.array([
    [1,2],
    [3,4]
])
tensor = np.array([
    [[1,2],[3,4]],
    [[5,6],[7,8]]
])
print("Scalar dimensions:", scalar.ndim)
print("Vector dimensions:", vector.ndim)
print("Matrix dimensions:", matrix.ndim)
print("Tensor dimensions:", tensor.ndim)

Scalar dimensions: 0
Vector dimensions: 1
Matrix dimensions: 2
Tensor dimensions: 3


##Matrix Multiplication

In [27]:
import numpy as np
A = np.array([
    [1, 2],
    [3, 4]
])
B = np.array([
    [5, 6],
    [7, 8]
])
result = np.matmul(A, B)
print(result)

[[19 22]
 [43 50]]


In [28]:
#Multiply a Matrix by a Vector
import numpy as np
A = np.array([
    [1,2],
    [3,4]
])
v = np.array([5,6])
result = A @ v
print(result)

[17 39]


In [30]:
#Check Matrix Shapes Before Multiply
import numpy as np
A = np.array([
    [1,2],
    [3,4]
])
B = np.array([
    [5,6],
    [7,8]
])
print("Shape of A:", A.shape)
print("Shape of B:", B.shape)
result = A @ B
print(result)

Shape of A: (2, 2)
Shape of B: (2, 2)
[[19 22]
 [43 50]]


##Mean

In [32]:
from statistics import mean
num = [10, 20, 30, 40, 50]
avg = mean(num)
print("Mean:", avg)

Mean: 30


##Median

In [33]:
from statistics import median
numbers = [12, 18, 20, 25, 30]
print("Median:", median(numbers))

Median: 20


In [34]:
from statistics import median
num = [5, 10, 15, 20]
print("Median:", median(num))

Median: 12.5


##Mode

In [37]:
from statistics import mode
num = [2, 4, 4, 5, 6, 6, 6, 8]
print("Mode:",mode(num))

Mode: 6
