#NUMPY


In [4]:
import numpy as np
arr=np.array([10,20,30,40,50])
print(arr)

[10 20 30 40 50]


In [1]:
#create an array of zeros of size 5
import numpy as np 

arr = np.zeros(5)
print(arr)

[0. 0. 0. 0. 0.]


In [2]:
import numpy as np

arr = np.ones((3,4))
print(arr)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [3]:
import numpy as np

arr = np.arange(1,21)
print(arr)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]


In [4]:
import numpy as np

arr = np.linspace(0,1,10)
print(arr)

[0.         0.11111111 0.22222222 0.33333333 0.44444444 0.55555556
 0.66666667 0.77777778 0.88888889 1.        ]


In [5]:
import numpy as np

arr = np.array([[1,2,3],[4,5,6]])

print(arr.shape)

(2, 3)


In [6]:
import numpy as np

arr = np.array([[1,2,3],[4,5,6]])

print(arr.ndim)

2


In [7]:
import numpy as np

arr = np.arange(12)

new_arr = arr.reshape(3,4)

print(new_arr)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [8]:
import numpy as np

arr = np.array([5,9,3,12,8])

print("Maximum:", arr.max())
print("Minimum:", arr.min())

Maximum: 12
Minimum: 3


In [9]:
import numpy as np

arr = np.array([2,4,6,8])

print(arr.sum())
print(arr.mean())

20
5.0


In [10]:
import numpy as np

a = np.array([1,2,3])

b = np.array([4,5,6])

print(a * b)

[ 4 10 18]


NumPy Broadcasting

In [ ]:
#Add a scalar value (10) to every element of an array.
import numpy as np
arr = np.array([1,2,3,4,5])
result = arr + 10
print(result)

[11 12 13 14 15]


In [ ]:
#Multiply every element of an array by 5 using broadcasting.
import numpy as np
arr = np.array([2,4,6,8])
result = arr * 5
print(result)

[10 20 30 40]


In [13]:
#Add a 1D array to each row of a 2D array.
import numpy as np
A = np.array([[1,2,3],[4,5,6],[7,8,9]])
B = np.array([10,20,30])
result = A + B
print(result)

[[11 22 33]
 [14 25 36]
 [17 28 39]]


In [14]:
#Add a column vector to every column.
import numpy as np
A = np.array([[1,2,3],[4,5,6],[7,8,9]])
B = np.array([[10],[20],[30]])
result = A + B
print(result)

[[11 12 13]
 [24 25 26]
 [37 38 39]]


In [ ]:
#Subtract one array from another using broadcasting.
import numpy as np
A = np.array([[10,20,30],[40,50,60]])
B = np.array([1,2,3])
print(A-B)

[[ 9 18 27]
 [39 48 57]]


In [17]:
#Divide each row by a 1D array.
import numpy as np
A = np.array([[10,20],[30,40]])
B = np.array([10,20])
print(A/B)

[[1. 1.]
 [3. 2.]]


In [18]:
#Divide each row by a 1D array.
import numpy as np
A = np.array([[1,2,3],[4,5,6]])
B = np.array([[10],[20]])
print(A*B)

[[ 10  20  30]
 [ 80 100 120]]


##Pandas

In [19]:
!pip install pandas

  Using cached pandas-3.0.3-cp311-cp311-win_amd64.whl.metadata (19 kB)
  Using cached tzdata-2026.3-py2.py3-none-any.whl.metadata (1.4 kB)
Using cached pandas-3.0.3-cp311-cp311-win_amd64.whl (9.9 MB)
Using cached tzdata-2026.3-py2.py3-none-any.whl (348 kB)

   ---------------------------------------- 0/2 [tzdata]
   ---------------------------------------- 0/2 [tzdata]
   ---------------------------------------- 0/2 [tzdata]
   ---------------------------------------- 0/2 [tzdata]
   ---------------------------------------- 0/2 [tzdata]
   ---------------------------------------- 0/2 [tzdata]
   ---------------------------------------- 0/2 [tzdata]
   ---------------------------------------- 0/2 [tzdata]
   ---------------------------------------- 0/2 [tzdata]
   ---------------------------------------- 0/2 [tzdata]
   ---------------------------------------- 0/2 [tzdata]
   ---------------------------------------- 0/2 [tzdata]
   ---------------------------------------- 0/2 [tzdata]
 

In [ ]:
#Create a DataFrame from a dictionary
import pandas as pd
data = {"Name": ["Alice", "Bob", "Charlie"],
    "Age": [25, 30, 35],
    "City": ["New York", "London", "Paris"]
}
df = pd.DataFrame(data)
print(df)

      Name  Age      City
0    Alice   25  New York
1      Bob   30    London
2  Charlie   35     Paris


In [21]:
#Display the first 5 rows of a DataFrame
import pandas as pd
data = {
    "Name": ["Alice", "Bob", "Charlie", "David", "Eva", "Frank"],
    "Age": [25, 30, 35, 28, 32, 40]
}
df = pd.DataFrame(data)
print(df.head())

      Name  Age
0    Alice   25
1      Bob   30
2  Charlie   35
3    David   28
4      Eva   32


In [22]:
#Display the last 3 rows
import pandas as pd
df = pd.DataFrame({
    "Name": ["A", "B", "C", "D", "E", "F"],
    "Age": [21, 22, 23, 24, 25, 26]
})
print(df.tail(3))

  Name  Age
3    D   24
4    E   25
5    F   26


In [23]:
#Display column names
import pandas as pd
df = pd.DataFrame({
    "Name": ["Alice", "Bob"],
    "Age": [25, 30]
})
print(df.columns)

Index(['Name', 'Age'], dtype='str')


In [24]:
#Select a single column
import pandas as pd
df = pd.DataFrame({
    "Name": ["Alice", "Bob"],
    "Age": [25, 30]
})
print(df["Name"])

0    Alice
1      Bob
Name: Name, dtype: str


In [25]:
#Select multiple columns
import pandas as pd
df = pd.DataFrame({
    "Name": ["Alice", "Bob"],
    "Age": [25, 30],
    "Salary": [50000, 60000]
})
print(df[["Name", "Salary"]])

    Name  Salary
0  Alice   50000
1    Bob   60000


Reading CSV 

In [26]:
import pandas as pd
df = pd.read_csv("C:/Users/91949/Downloads/employees.csv")
print(df.head())

   EMPLOYEE_ID FIRST_NAME  LAST_NAME     EMAIL  PHONE_NUMBER  HIRE_DATE  \
0          198     Donald   OConnell  DOCONNEL  650.507.9833  21-JUN-07   
1          199    Douglas      Grant    DGRANT  650.507.9844  13-JAN-08   
2          200   Jennifer     Whalen   JWHALEN  515.123.4444  17-SEP-03   
3          201    Michael  Hartstein  MHARTSTE  515.123.5555  17-FEB-04   
4          202        Pat        Fay      PFAY  603.123.6666  17-AUG-05   

     JOB_ID  SALARY COMMISSION_PCT MANAGER_ID  DEPARTMENT_ID  
0  SH_CLERK    2600             -         124             50  
1  SH_CLERK    2600             -         124             50  
2   AD_ASST    4400             -         101             10  
3    MK_MAN   13000             -         100             20  
4    MK_REP    6000             -         201             20  


In [ ]:
#Read an Excel file
import pandas as pd
df = pd.read_excel("C:/Users/91949/Downloads/employees.xlsx")
print(df.head())

In [ ]:
#Read a JSON file
import pandas as pd
df = pd.read_json("employees.json")
print(df.head())

In [30]:
#Save a DataFrame to CSV
import pandas as pd
data = {
    "Name": ["Alice", "Bob"],
    "Age": [25, 30]
}
df = pd.DataFrame(data)
df.to_csv("outputName.csv", index=False)

Filtering

In [31]:
import pandas as pd
df = pd.DataFrame({
    "Name":["Ram","Babu","Chary","David"],
    "Age":[25,32,28,40],
    "Salary":[50000,70000,60000,90000]
})

In [32]:
#Employees older than 30
print(df[df["Age"] > 30])

    Name  Age  Salary
1   Babu   32   70000
3  David   40   90000


In [33]:
#Salary greater than 60000
print(df[df["Salary"] > 60000])

    Name  Age  Salary
1   Babu   32   70000
3  David   40   90000


In [34]:
#Multiple conditions
print(df[(df["Age"] > 25) & (df["Salary"] > 60000)])

    Name  Age  Salary
1   Babu   32   70000
3  David   40   90000


In [35]:
#Select only Name and Salary where Age > 25
print(df.loc[df["Age"] > 25, ["Name", "Salary"]])

    Name  Salary
1   Babu   70000
2  Chary   60000
3  David   90000


In [36]:
#Filter names equal to "RAM"
print(df[df["Name"] == "Ram"])

  Name  Age  Salary
0  Ram   25   50000


GroupBy


In [37]:
import pandas as pd
df = pd.DataFrame({
    "Department":["HR","IT","HR","IT","Sales"],
    "Salary":[50000,70000,55000,80000,60000]
})

In [38]:
import pandas as pd

df = pd.DataFrame({
    "Department":["HR","IT","HR","IT","Sales"],
    "Salary":[50000,70000,55000,80000,60000]
})

In [39]:
print(df.groupby("Department")["Salary"].mean())

Department
HR       52500.0
IT       75000.0
Sales    60000.0
Name: Salary, dtype: float64
